name: build

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu', 'windows']
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7
        with:
          submodules: 'recursive' 
      - name: build
        run: ./ci/ci.bash
        shell: bash
      - name: upload-artifacts
        uses: actions/upload-artifact@v4.3.6
        with:
          name: godot-pure-data-${{ matrix.os }}
          path: work/install
  
  package:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7
      - name: download all build artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          path: work/artifacts
      - name: build
        run: sh ci/package.bash work/artifacts
        shell: bash
      - name: upload-artifacts
        uses: actions/upload-artifact@v4.3.6
        with:
          name: project
          path: addons

  publish:
    needs: [package]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7
        with:
          ref: master
      - name: download all build artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          name: project
          path: addons
      - name: commit
        run: |
          git config --global user.name 'samsface'
          git config --global user.email 'samsface@users.noreply.github.com'
          git add -A
          git commit -am "automated commit"
          git push

  remove-old-artifacts:
    needs: [publish]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: remove-old-artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '10 minutes'
